events { }
http {
    error_log stderr debug;
    server {
      listen               9443 ssl default_server;
      ssl_reject_handshake on;
    }
    server {
      listen               9443 ssl;
      server_name          api.localhost;
      ssl_certificate      ssl/api.localhost.crt;
      ssl_certificate_key  ssl/api.localhost.key;
      index                index.html;
    }
}
