events { }
http {
    error_log stderr debug;
    server {
      listen               8443 ssl default_server;
      server_name          api.localhost;
      ssl_certificate      ssl/api.localhost.crt;
      ssl_certificate_key  ssl/api.localhost.key;
      index                empty;
    }
}
